version: "3.1"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: care-compass-client
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
